version: "3"

services:
  ubuntu-learn:
    image: zhoupro/learn
    privileged: true
    shm_size: '2gb'
    volumes:
      - .:/root/workspace
      - ./conf/rc.lua:/root/.config/awesome/rc.lua
      - ./conf/konsole/konsolerc:/root/.config/konsolerc
      - ./conf/konsole/konsole:/root/.local/share/konsole
    ports:
      - "5900:5900"
      - "9999:9999"
    environment:
      SIZE: 4096x2160
      PASSWD: docker


