version: "3"

services:
  ubuntu-desktop:
    image: gotoeasy/ubuntu-desktop
    privileged: true
    shm_size: '2gb'
    volumes:
      - .:/root/workspace
    ports:
      - "10022:22"
      - "5900:5900"
      - "6080:6080"
      - "5901:5901"
      - "13389:3389"
    environment:
      SIZE: 1920x1080
      PASSWD: 123456
