version: "3"

services:
  ubuntu-desktop:
    image: prozhou/ubuntu-desktop
    privileged: true
    shm_size: '2gb'
    volumes:
      - .:/root/workspace
    ports:
      - "5900:5900"
    environment:
      SIZE: 1920x1080
      PASSWD: 123456
